# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/Cr_work/Lab1012/FPGA/eth_udp_loop/eth_udp_loop.srcs/sources_1/ip/clk_wiz_1/clk_wiz.xci
# IP: The module: 'clk_wiz' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Cr_work/Lab1012/FPGA/eth_udp_loop/eth_udp_loop.srcs/sources_1/ip/clk_wiz_1/clk_wiz_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: e:/Cr_work/Lab1012/FPGA/eth_udp_loop/eth_udp_loop.srcs/sources_1/ip/clk_wiz_1/clk_wiz.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: e:/Cr_work/Lab1012/FPGA/eth_udp_loop/eth_udp_loop.srcs/sources_1/ip/clk_wiz_1/clk_wiz_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: e:/Cr_work/Lab1012/FPGA/eth_udp_loop/eth_udp_loop.srcs/sources_1/ip/clk_wiz_1/clk_wiz.xci
# IP: The module: 'clk_wiz' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Cr_work/Lab1012/FPGA/eth_udp_loop/eth_udp_loop.srcs/sources_1/ip/clk_wiz_1/clk_wiz_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: e:/Cr_work/Lab1012/FPGA/eth_udp_loop/eth_udp_loop.srcs/sources_1/ip/clk_wiz_1/clk_wiz.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: e:/Cr_work/Lab1012/FPGA/eth_udp_loop/eth_udp_loop.srcs/sources_1/ip/clk_wiz_1/clk_wiz_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
