create_clock -period 20.000 -name sys_clk [get_ports sys_clk]
create_clock -period 8.000 -name eth_rxc [get_ports eth_rxc]
set_property -dict {PACKAGE_PIN R4 IOSTANDARD LVCMOS15} [get_ports sys_clk]
set_property -dict {PACKAGE_PIN U7 IOSTANDARD LVCMOS15} [get_ports sys_rst_n]

set_property -dict {PACKAGE_PIN N20 IOSTANDARD LVCMOS33} [get_ports eth_rst_n]
set_property -dict {PACKAGE_PIN U20 IOSTANDARD LVCMOS33} [get_ports eth_rxc]
set_property -dict {PACKAGE_PIN AA20 IOSTANDARD LVCMOS33} [get_ports eth_rx_ctl]
set_property -dict {PACKAGE_PIN AA21 IOSTANDARD LVCMOS33} [get_ports {eth_rxd[0]}]
set_property -dict {PACKAGE_PIN V20 IOSTANDARD LVCMOS33} [get_ports {eth_rxd[1]}]
set_property -dict {PACKAGE_PIN U22 IOSTANDARD LVCMOS33} [get_ports {eth_rxd[2]}]
set_property -dict {PACKAGE_PIN V22 IOSTANDARD LVCMOS33} [get_ports {eth_rxd[3]}]

set_property -dict {PACKAGE_PIN V18 IOSTANDARD LVCMOS33} [get_ports eth_txc]
set_property -dict {PACKAGE_PIN V19 IOSTANDARD LVCMOS33} [get_ports eth_tx_ctl]
set_property -dict {PACKAGE_PIN T21 IOSTANDARD LVCMOS33} [get_ports {eth_txd[0]}]
set_property -dict {PACKAGE_PIN U21 IOSTANDARD LVCMOS33} [get_ports {eth_txd[1]}]
set_property -dict {PACKAGE_PIN P19 IOSTANDARD LVCMOS33} [get_ports {eth_txd[2]}]
set_property -dict {PACKAGE_PIN R19 IOSTANDARD LVCMOS33} [get_ports {eth_txd[3]}]



# set_property -dict {PACKAGE_PIN Y18 IOSTANDARD LVCMOS33} [get_ports eth_rxc1]
# set_property -dict {PACKAGE_PIN Y21 IOSTANDARD LVCMOS33} [get_ports eth_rx_ctl1]
# set_property -dict {PACKAGE_PIN Y22 IOSTANDARD LVCMOS33} [get_ports {eth_rxd1[0]}]
# set_property -dict {PACKAGE_PIN AB21 IOSTANDARD LVCMOS33} [get_ports {eth_rxd1[1]}]
# set_property -dict {PACKAGE_PIN AB22 IOSTANDARD LVCMOS33} [get_ports {eth_rxd1[2]}]
# set_property -dict {PACKAGE_PIN Y19 IOSTANDARD LVCMOS33} [get_ports {eth_rxd1[3]}]

# set_property -dict {PACKAGE_PIN P20 IOSTANDARD LVCMOS33} [get_ports eth_txc1]
# set_property -dict {PACKAGE_PIN T20 IOSTANDARD LVCMOS33} [get_ports eth_tx_ctl1]
# set_property -dict {PACKAGE_PIN W21 IOSTANDARD LVCMOS33} [get_ports {eth_txd1[0]}]
# set_property -dict {PACKAGE_PIN W22 IOSTANDARD LVCMOS33} [get_ports {eth_txd1[1]}]
# set_property -dict {PACKAGE_PIN W19 IOSTANDARD LVCMOS33} [get_ports {eth_txd1[2]}]
# set_property -dict {PACKAGE_PIN W20 IOSTANDARD LVCMOS33} [get_ports {eth_txd1[3]}]

set_property PACKAGE_PIN Y22 [get_ports {eth_rxd1[0]}]
set_property PACKAGE_PIN AB21 [get_ports {eth_rxd1[1]}]
set_property PACKAGE_PIN AB22 [get_ports {eth_rxd1[2]}]
set_property PACKAGE_PIN Y19 [get_ports {eth_rxd1[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {eth_rxd1[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {eth_rxd1[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {eth_rxd1[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {eth_rxd1[0]}]
set_property PACKAGE_PIN W22 [get_ports {eth_txd1[0]}]
set_property PACKAGE_PIN T20 [get_ports {eth_txd1[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {eth_txd1[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {eth_txd1[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {eth_txd1[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {eth_txd1[0]}]
set_property PACKAGE_PIN Y21 [get_ports eth_rx_ctl1]
set_property IOSTANDARD LVCMOS33 [get_ports eth_tx_ctl1]
set_property IOSTANDARD LVCMOS33 [get_ports eth_txc1]
set_property IOSTANDARD LVCMOS33 [get_ports eth_rxc1]
set_property IOSTANDARD LVCMOS33 [get_ports eth_rx_ctl1]

set_property PACKAGE_PIN V9 [get_ports led]
set_property IOSTANDARD LVCMOS15 [get_ports led]

set_property PACKAGE_PIN E14 [get_ports uart_rxd]
set_property IOSTANDARD LVCMOS33 [get_ports uart_rxd]
set_property PACKAGE_PIN D17 [get_ports uart_txd]
set_property IOSTANDARD LVCMOS33 [get_ports uart_txd]

set_property PACKAGE_PIN W21 [get_ports {eth_txd1[1]}]
set_property PACKAGE_PIN W20 [get_ports eth_tx_ctl1]
set_property PACKAGE_PIN Y18 [get_ports eth_rxc1]
set_property PACKAGE_PIN W19 [get_ports eth_txc1]
set_property PACKAGE_PIN P20 [get_ports {eth_txd1[3]}]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets clk_200m]
